import {
  mdiClose,
  mdiHome,
  mdiEyeOff,
  mdiEye,
  mdiFacebook,
  mdiCog,
  mdiTwitter,
  mdiInstagram,
  mdiLinkedin,
  mdiGoogle,
  mdiYoutube,
  mdiMonitorDashboard, 
  mdiLogin,
  mdiAccountGroup,
  mdiCurrencyUsd,
  mdiEarth,
  mdiShieldCheck,
} from '@mdi/js';

export const icons = {
  close: mdiClose,
  home: mdiHome,
  eyeOff: mdiEyeOff,
  eye: mdiEye,
  facebook: mdiFacebook,
  twitter: mdiTwitter,
  instagram: mdiInstagram,
  linkedin: mdiLinkedin,
  google: mdiGoogle,
  youtube: mdiYoutube,
  cog: mdiCog,
  dashboard: mdiMonitorDashboard,
  login: mdiLogin,
  users: mdiAccountGroup,
  'trading-volume': mdiCurrencyUsd,
  countries: mdiEarth,
  uptime: mdiShieldCheck
};
